// dvnet-data.js — Gerado pelo DV.NeT Admin
// Atualizado em: 26/05/2026, 23:23

(function(){
const DVNET_PRODUCTS=[{"id":1,"emoji":"🎧","badge":"VIRAL","name":"HEADSET GAMER ALPHA Sdedd","brand":"HyperX","cat":"headset","desc":"Som surround 7.1 virtual, microfone com cancelamento de ruído, conforto premium.","img":"","priceOrig":649,"priceSale":289.9,"coupon":"DVNET20","couponPct":"-20% EXTRA","link":"#","views":68,"units":"7 unidades","stars":5,"reviews":1247},{"id":2,"emoji":"🖱️","name":"Mouse Gamer Logitech G502X","brand":"Logitech","cat":"mouse","desc":"25K DPI · Wireless · 89g","img":"","badge":"HOT","priceOrig":699,"priceSale":399.9,"coupon":"","couponPct":"","link":"#","views":23,"units":"Estoque alto","stars":5,"reviews":892},{"id":3,"emoji":"⌨️","name":"Teclado Mecânico TKL RGB","brand":"","cat":"teclado","desc":"Switch Red · PBT Doubleshot","img":"","badge":"","priceOrig":449,"priceSale":249.9,"coupon":"","couponPct":"","link":"#","views":15,"units":"","stars":4.5,"reviews":341},{"id":4,"emoji":"🖥️","name":"Monitor Curvo 27\" 165Hz","brand":"","cat":"monitor","desc":"QHD 2K · 1ms · FreeSync","img":"","badge":"","priceOrig":1999,"priceSale":1299.9,"coupon":"","couponPct":"","link":"#","views":41,"units":"","stars":5,"reviews":654},{"id":5,"emoji":"💺","name":"Cadeira Gamer DXRacer Elite","brand":"DXRacer","cat":"cadeira","desc":"Couro Premium · Lombar 4D","img":"","badge":"","priceOrig":1899,"priceSale":1099,"coupon":"","couponPct":"","link":"#","views":12,"units":"","stars":4.5,"reviews":289},{"id":6,"emoji":"📷","name":"Webcam StreamCam 1080p 60fps","brand":"Logitech","cat":"webcam","desc":"Ideal para lives e home office","img":"","badge":"HOT","priceOrig":599,"priceSale":359,"coupon":"DVNET10","couponPct":"-10% extra","link":"#","views":23,"units":"12 unid.","stars":5,"reviews":1247},{"id":7,"emoji":"🎮","name":"Controle Xbox Elite Series 2","brand":"Xbox","cat":"controle","desc":"Botões traseiros · Trigger lock · Wireless","img":"","badge":"VIRAL","priceOrig":1499,"priceSale":569,"coupon":"GAMER20","couponPct":"-20% extra","link":"#","views":87,"units":"3 unid.","stars":5,"reviews":2341},{"id":8,"emoji":"🎙️","name":"Microfone Condensador USB Pro","brand":"Blue Yeti","cat":"microfone","desc":"Cardioide · Plug & Play · 48kHz","img":"","badge":"","priceOrig":1099,"priceSale":604,"coupon":"MIC10","couponPct":"-10% extra","link":"#","views":15,"units":"Estoque alto","stars":5,"reviews":3102}];
const DVNET_BLOGS=[{"id":1,"title":"HyperX Cloud Alpha S: Vale os R$290?","cat":"Review","read":"5 min","desc":"Testamos o headset por 30 dias e chegamos a uma conclusão definitiva.","img":"","link":"#","views":42891,"date":"2025-05-20"},{"id":2,"title":"Setup Gamer por R$2.000: Guia Definitivo 2025","cat":"Guia","read":"12 min","desc":"Montamos o melhor setup gamer possível sem estourar o orçamento.","img":"","link":"#","views":98112,"date":"2025-05-18"},{"id":3,"title":"10 Melhores Mouses Gamer de 2025","cat":"Top 10","read":"8 min","desc":"Comparamos os top 10 mouses do mercado em todas as faixas de preço.","img":"","link":"#","views":71440,"date":"2025-05-15"}];
const DVNET_TRENDS=[{"id":1,"emoji":"🎮","name":"Controle Xbox Elite Series 2","cat":"Controle","change":"+127%","link":"#","badge":"🔥 VIRAL"},{"id":2,"emoji":"🎧","name":"HyperX Cloud Alpha S","cat":"Headset","change":"+89%","link":"#","badge":""},{"id":3,"emoji":"🖱️","name":"Mouse Logitech G502X","cat":"Mouse","change":"+63%","link":"#","badge":""},{"id":4,"emoji":"⌨️","name":"Teclado Mecânico TKL","cat":"Teclado","change":"+41%","link":"#","badge":"🆕 NOVO"},{"id":5,"emoji":"📷","name":"Webcam StreamCam 1080p","cat":"Webcam","change":"+35%","link":"#","badge":""}];
const DVNET_CUPONS=[{"id":1,"code":"DVNET20","pct":"-20%","store":"Amazon · Headsets","desc":"","exp":"2025-12-31","status":"ativo"},{"id":2,"code":"GAMER15","pct":"-15%","store":"Amazon · Teclados e Mouses","desc":"","exp":"2025-11-30","status":"ativo"},{"id":3,"code":"FLASH30","pct":"-30%","store":"Amazon · Oferta relâmpago","desc":"Apenas para a oferta do dia","exp":"2025-06-30","status":"ativo"},{"id":4,"code":"SETUP10","pct":"-10%","store":"Amazon · Monitores","desc":"","exp":"2025-10-31","status":"ativo"},{"id":5,"code":"MIC10","pct":"-10%","store":"Amazon · Microfones","desc":"","exp":"2025-09-30","status":"ativo"},{"id":6,"code":"CHAIR25","pct":"-25%","store":"Amazon · Cadeiras Gamer","desc":"","exp":"2025-08-31","status":"ativo"}];

function fmt(n){return(+n).toLocaleString('pt-BR',{minimumFractionDigits:2});}
function disc(o,s){return o>0&&s>0?Math.round((1-(s/o))*100):0;}
function stars(n){return'★'.repeat(Math.floor(n))+(n%1>=.5?'½':'')+'☆'.repeat(5-Math.ceil(n));}

function renderProducts(){
  const sec=document.getElementById('products')||document.querySelector('section[id*="product"]');
  if(!sec)return;
  let grid=sec.querySelector('.dvnet-injected');
  if(!grid){grid=document.createElement('div');grid.className='dvnet-injected';grid.style.cssText='display:grid;grid-template-columns:repeat(auto-fill,minmax(260px,1fr));gap:20px;padding:0 5%';sec.appendChild(grid);}
  grid.innerHTML=DVNET_PRODUCTS.map(p=>{const d=disc(p.priceOrig,p.priceSale);return `<div style="background:#1a1a2e;border:1px solid #ffffff1a;border-radius:14px;overflow:hidden"><div style="height:120px;background:#16162a;display:flex;align-items:center;justify-content:center;font-size:44px;position:relative">${p.img?'<img src="'+p.img+'" style="width:100%;height:100%;object-fit:cover">':'<span>'+p.emoji+'</span>'}${p.badge?'<span style="position:absolute;top:8px;left:8px;background:#ff4d00;color:#fff;font-size:10px;font-weight:700;padding:2px 7px;border-radius:5px">'+p.badge+'</span>':''}${d?'<span style="position:absolute;top:8px;right:8px;background:#00d97e;color:#000;font-size:10px;font-weight:700;padding:2px 7px;border-radius:5px">-'+d+'%</span>':''}</div><div style="padding:14px">${p.brand?'<div style="font-size:10px;color:#8888aa;font-weight:600;text-transform:uppercase;margin-bottom:3px">'+p.brand+'</div>':''}<div style="font-size:14px;font-weight:700;margin-bottom:6px;color:#f0f0ff">${p.name}</div>${p.desc?'<div style="font-size:12px;color:#8888aa;margin-bottom:8px">'+p.desc+'</div>':''}<div style="display:flex;align-items:baseline;gap:8px;margin-bottom:6px"><span style="font-size:20px;font-weight:700;color:#ff4d00">R$${fmt(p.priceSale)}</span>${p.priceOrig?'<span style="font-size:12px;color:#8888aa;text-decoration:line-through">R$'+fmt(p.priceOrig)+'</span>':''}</div>${p.coupon?'<div style="font-size:11px;background:#00d97e15;color:#00d97e;padding:4px 8px;border-radius:6px;margin-bottom:8px;display:inline-block">🎟️ <b>'+p.coupon+'</b> '+p.couponPct+'</div>':''}<a href="${p.link}" target="_blank" rel="noopener" style="display:block;padding:10px;background:#ff4d00;color:#fff;border-radius:8px;font-weight:700;font-size:13px;text-align:center;text-decoration:none">🛒 VER OFERTA</a></div></div>`;}).join('');
}

function renderBlog(){
  const sec=document.getElementById('blog');if(!sec||!DVNET_BLOGS.length)return;
  let grid=sec.querySelector('.dvnet-blog');if(!grid){grid=document.createElement('div');grid.className='dvnet-blog';grid.style.cssText='display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:20px;padding:0 5%';sec.appendChild(grid);}
  grid.innerHTML=DVNET_BLOGS.map(b=>`<div style="background:#1a1a2e;border:1px solid #ffffff1a;border-radius:14px;overflow:hidden"><div style="padding:16px"><span style="font-size:10px;font-weight:700;background:#ff4d0020;color:#ff4d00;padding:2px 7px;border-radius:5px">${b.cat.toUpperCase()}</span><div style="font-size:15px;font-weight:700;margin:8px 0 6px;color:#f0f0ff">${b.title}</div>${b.desc?'<div style="font-size:12px;color:#8888aa;margin-bottom:8px">'+b.desc+'</div>':''}<div style="font-size:11px;color:#8888aa">${b.read?'⏱ '+b.read+' · ':''}${b.views?'👁 '+b.views.toLocaleString('pt-BR')+' views':''}</div></div></div>`).join('');
}

function renderTrending(){
  const sec=document.getElementById('trending');if(!sec||!DVNET_TRENDS.length)return;
  let list=sec.querySelector('.dvnet-trending');if(!list){list=document.createElement('div');list.className='dvnet-trending';list.style.cssText='display:flex;flex-direction:column;gap:10px;padding:0 5%';sec.appendChild(list);}
  list.innerHTML=DVNET_TRENDS.map((t,i)=>`<a href="${t.link||'#'}" target="_blank" rel="noopener" style="display:flex;align-items:center;gap:14px;padding:14px 18px;background:#1a1a2e;border:1px solid #ffffff1a;border-radius:12px;text-decoration:none"><span style="font-size:18px;font-weight:700;color:#ff4d00;width:24px">${String(i+1).padStart(2,'0')}</span><span style="font-size:20px">${t.emoji||'📦'}</span><div style="flex:1"><div style="font-size:14px;font-weight:600;color:#f0f0ff">${t.name}</div>${t.change?'<div style="font-size:12px;color:#00d97e">'+t.change+'</div>':''}</div></a>`).join('');
}

document.addEventListener('DOMContentLoaded',function(){renderProducts();renderBlog();renderTrending();});
})();