{
  "version": "1.0",
  "date": "2026-05-27T03:00:48.342Z",
  "products": [
    {
      "id": 1,
      "emoji": "🎧",
      "badge": "TOP",
      "name": "Havit H2002D",
      "brand": "Havit",
      "cat": "headset",
      "desc": "Havit Headphone Fone de Ouvido H2002d, Gamer, com Microfone, Falante 53mm, Plug 3, 5mm: compatível com XBOX ONE e PS4, HAVIT, HV-H2002d",
      "img": "https://m.media-amazon.com/images/I/71+kXnOiM2L._AC_SL1500_.jpg",
      "priceOrig": 294.6,
      "priceSale": 139.99,
      "coupon": "GAMER10",
      "couponPct": "-10% EXTRA",
      "link": "https://amzn.to/4x7PpXI",
      "views": 0,
      "units": "0",
      "stars": 5,
      "reviews": 1247
    },
    {
      "id": 2,
      "emoji": "📦",
      "badge": "VIRAL",
      "name": "Havit  Fuxi-H3",
      "brand": "Havit",
      "cat": "headset",
      "desc": "Havit Fone de Ouvido Headset Gamer Fuxi-H3",
      "img": "https://m.media-amazon.com/images/I/71g1gS6qGmL._AC_SX300_SY300_QL70_ML2_.jpg",
      "priceOrig": 265.45,
      "priceSale": 151.98,
      "coupon": "",
      "couponPct": "",
      "link": "#https://amzn.to/4wU6vYR",
      "views": 0,
      "units": "Estoque alto",
      "stars": 5,
      "reviews": 7157
    },
    {
      "id": 3,
      "emoji": "⌨️",
      "badge": "VIRAL",
      "name": "Headset ASTRO A10",
      "brand": "ASTRO ",
      "cat": "headset",
      "desc": "Headset Com Fio ASTRO A10 Gaming Gen 2 Com Microfone Flip-to-mute, Drivers de 32 mm, Compatível com PlayStation 5, PlayStation 4, Nintendo Switch, PC, Mac - Branco",
      "img": "https://m.media-amazon.com/images/I/61L6NgK5J4L._AC_SY300_SX300_QL70_ML2_.jpg",
      "priceOrig": 499.9,
      "priceSale": 384,
      "coupon": "",
      "couponPct": "",
      "link": "https://amzn.to/4uy6eZT",
      "views": -2,
      "units": "",
      "stars": 4,
      "reviews": 215
    },
    {
      "id": 4,
      "emoji": "🖥️",
      "badge": "VIRAL",
      "name": "Monitor Gamer LG UltraGear 27",
      "brand": "LG ULTRAGEAR",
      "cat": "monitor",
      "desc": "Monitor Gamer LG UltraGear 27” 27GS60F-B IPS Full HD 180Hz 1ms (GtG) NVIDIA® G-SYNC® AMD FreeSync™ HDR10 sRGB 99% HDMI DisplayPort",
      "img": "https://m.media-amazon.com/images/I/61GElLiaorL._AC_SL1000_.jpg",
      "priceOrig": 1.299,
      "priceSale": 1.019,
      "coupon": "GAMER100OFF ",
      "couponPct": "R$ 100,00 0FF",
      "link": "#https://amzn.to/4u3EE5Z",
      "views": 0,
      "units": "",
      "stars": 5,
      "reviews": 1962
    },
    {
      "id": 5,
      "emoji": "🖥️",
      "badge": "VIRAL",
      "name": "Monitor Gamer LG UltraGear 24",
      "brand": "LG ULTRAGEAR",
      "cat": "monitor",
      "desc": "Monitor Gamer LG UltraGear 27” 27GS60F-B IPS Full HD 180Hz 1ms (GtG) NVIDIA® G-SYNC® AMD FreeSync™ HDR10 sRGB 99% HDMI DisplayPort",
      "img": "https://m.media-amazon.com/images/I/61GElLiaorL._AC_SL1000_.jpg",
      "priceOrig": 1199,
      "priceSale": 834.71,
      "coupon": "GAMER10 ",
      "couponPct": "- 10% EXTRA",
      "link": "https://amzn.to/4dNANDV",
      "views": 0,
      "units": "",
      "stars": 4.5,
      "reviews": 4259
    },
    {
      "id": 6,
      "emoji": "📷",
      "badge": "VIRAL",
      "name": "Monitor LG UltraGear 27",
      "brand": "LG ULTRAGEAR",
      "cat": "monitor",
      "desc": "Monitor LG UltraGear 27GN750-27\" IPS Full HD, 240Hz, 1ms (GtG), NVIDIA G-Sync, HDMI, USB 3.0 e Ajustes de Inclinação, Preto",
      "img": "https://m.media-amazon.com/images/I/61bd+vWazsL._AC_SL1200_.jpg",
      "priceOrig": 2.199,
      "priceSale": 1.559,
      "coupon": "",
      "couponPct": "",
      "link": "https://amzn.to/4tZtMpw",
      "views": 0,
      "units": "",
      "stars": 4.5,
      "reviews": 283
    },
    {
      "id": 7,
      "emoji": "📦",
      "badge": "VIRAL",
      "name": "Redragon Kumara Pro V2",
      "brand": "REDRAGON",
      "cat": "teclado",
      "desc": "Teclado Magnético Gamer Redragon Kumara Pro V2 RGB Preto Switch Marrom K552RGB-PRO (PT-BROWN) V2",
      "img": "https://m.media-amazon.com/images/I/61nvk16RZrL._AC_SL1500_.jpg",
      "priceOrig": 369,
      "priceSale": 325,
      "coupon": "",
      "couponPct": "",
      "link": "https://amzn.to/4u15oUF",
      "views": 0,
      "units": "",
      "stars": 4.5,
      "reviews": 127
    },
    {
      "id": 8,
      "emoji": "🎙️",
      "badge": "VIRAL",
      "name": "Redragon Dark Avenge",
      "brand": "REDRAGON",
      "cat": "teclado",
      "desc": "Teclado Mecânico Redragon Dark Avenger RGB Lunar White Switch Vermelho K568W-RGB",
      "img": "https://m.media-amazon.com/images/I/51xoetNmlOL._AC_SL1000_.jpg",
      "priceOrig": 184.9,
      "priceSale": 175,
      "coupon": "",
      "couponPct": "",
      "link": "https://amzn.to/4nSiguQ",
      "views": 0,
      "units": "",
      "stars": 5,
      "reviews": 160
    },
    {
      "id": 1779850408100,
      "emoji": "📦",
      "badge": "VIRAL",
      "name": "Redragon Fizz RGB",
      "brand": "REDRAGON",
      "cat": "teclado",
      "desc": "Teclado Magnético Gamer Redragon Fizz RGB Preto 60% Polling Rate 8K Rapid Trigger Switch Linear K617RGB-M",
      "img": "https://m.media-amazon.com/images/I/61iF9YbMcEL._AC_SL1500_.jpg",
      "priceOrig": 301.28,
      "priceSale": 188,
      "coupon": "",
      "couponPct": "",
      "link": "https://amzn.to/4dLjgMr",
      "views": 0,
      "units": "",
      "stars": 5,
      "reviews": 31
    }
  ],
  "blogs": [
    {
      "id": 1,
      "title": "HyperX Cloud Alpha S: Vale os R$290?",
      "cat": "Review",
      "read": "5 min",
      "desc": "Testamos o headset por 30 dias e chegamos a uma conclusão definitiva.",
      "img": "",
      "link": "#",
      "views": 42891,
      "date": "2025-05-20"
    },
    {
      "id": 2,
      "title": "Setup Gamer por R$2.000: Guia Definitivo 2025",
      "cat": "Guia",
      "read": "12 min",
      "desc": "Montamos o melhor setup gamer possível sem estourar o orçamento.",
      "img": "",
      "link": "#",
      "views": 98112,
      "date": "2025-05-18"
    },
    {
      "id": 3,
      "title": "10 Melhores Mouses Gamer de 2025",
      "cat": "Top 10",
      "read": "8 min",
      "desc": "Comparamos os top 10 mouses do mercado em todas as faixas de preço.",
      "img": "",
      "link": "#",
      "views": 71440,
      "date": "2025-05-15"
    }
  ],
  "trends": [
    {
      "id": 1,
      "emoji": "🎮",
      "name": "Controle Xbox Elite Series 2",
      "cat": "Controle",
      "change": "+127%",
      "link": "#",
      "badge": "🔥 VIRAL"
    },
    {
      "id": 2,
      "emoji": "🎧",
      "name": "HyperX Cloud Alpha S",
      "cat": "Headset",
      "change": "+89%",
      "link": "#",
      "badge": ""
    },
    {
      "id": 3,
      "emoji": "🖱️",
      "name": "Mouse Logitech G502X",
      "cat": "Mouse",
      "change": "+63%",
      "link": "#",
      "badge": ""
    },
    {
      "id": 4,
      "emoji": "⌨️",
      "name": "Teclado Mecânico TKL",
      "cat": "Teclado",
      "change": "+41%",
      "link": "#",
      "badge": "🆕 NOVO"
    },
    {
      "id": 5,
      "emoji": "📷",
      "name": "Webcam StreamCam 1080p",
      "cat": "Webcam",
      "change": "+35%",
      "link": "#",
      "badge": ""
    }
  ],
  "cupons": [
    {
      "id": 1,
      "code": "DVNET20",
      "pct": "-20%",
      "store": "Amazon · Headsets",
      "desc": "",
      "exp": "2025-12-31",
      "status": "ativo"
    },
    {
      "id": 2,
      "code": "GAMER15",
      "pct": "-15%",
      "store": "Amazon · Teclados e Mouses",
      "desc": "",
      "exp": "2025-11-30",
      "status": "ativo"
    },
    {
      "id": 3,
      "code": "FLASH30",
      "pct": "-30%",
      "store": "Amazon · Oferta relâmpago",
      "desc": "Apenas para a oferta do dia",
      "exp": "2025-06-30",
      "status": "ativo"
    },
    {
      "id": 4,
      "code": "SETUP10",
      "pct": "-10%",
      "store": "Amazon · Monitores",
      "desc": "",
      "exp": "2025-10-31",
      "status": "ativo"
    },
    {
      "id": 5,
      "code": "MIC10",
      "pct": "-10%",
      "store": "Amazon · Microfones",
      "desc": "",
      "exp": "2025-09-30",
      "status": "ativo"
    },
    {
      "id": 6,
      "code": "CHAIR25",
      "pct": "-25%",
      "store": "Amazon · Cadeiras Gamer",
      "desc": "",
      "exp": "2025-08-31",
      "status": "ativo"
    }
  ],
  "oferta": {
    "emoji": "🎮",
    "name": "Controle Xbox Elite Series 2",
    "priceOrig": 1499,
    "priceSale": 569,
    "coupon": "GAMER20",
    "couponPct": "-20% extra",
    "link": "#",
    "hours": 6,
    "units": "Apenas 3 restantes!"
  }
}
